FROM golang:1.18-alpine

RUN apk add --update \
  curl \
  && rm -rf /var/cache/apk/*

RUN curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

WORKDIR /app

COPY . .

RUN go mod download

EXPOSE 8081 

CMD [ "air" ]
